// src/lib/bracket-rules.ts

export type SlotSource =
  | { kind: "group-1"; group: string }
  | { kind: "group-2"; group: string }
  | { kind: "group-3"; group: string }
  | { kind: "match-winner"; matchId: string }

export type BracketSlot = {
  matchId: string
  slotA: SlotSource
  slotB: SlotSource
}

export type ThirdSlot = {
  matchId: string
  slot: "A" | "B"
  group: string
}

/**
 * FIFA 2026 official R32 bracket.
 *
 * 8 matches: group winner (slotA) vs 3rd-place team (slotB, group="?").
 *   slotB for these matches is overridden by THIRD_PLACE_TABLE in propagateBracket.
 *   Matches: r32-3(W-E), r32-6(W-I), r32-7(W-A), r32-8(W-L),
 *            r32-9(W-D), r32-10(W-G), r32-13(W-B), r32-16(W-K)
 *
 * 4 matches: group winner vs runner-up (cross-group).
 *   r32-2(W-C/RU-F), r32-4(W-F/RU-C), r32-11(W-H/RU-J), r32-15(W-J/RU-H)
 *
 * 4 matches: runner-up vs runner-up.
 *   r32-1(RU-A/RU-B), r32-5(RU-E/RU-I), r32-12(RU-K/RU-L), r32-14(RU-D/RU-G)
 */
export const R32_BRACKET: BracketSlot[] = [
  { matchId: "r32-1",  slotA: { kind: "group-2", group: "A" }, slotB: { kind: "group-2", group: "B" } },
  { matchId: "r32-2",  slotA: { kind: "group-1", group: "C" }, slotB: { kind: "group-2", group: "F" } },
  { matchId: "r32-3",  slotA: { kind: "group-1", group: "E" }, slotB: { kind: "group-3", group: "?" as string } },
  { matchId: "r32-4",  slotA: { kind: "group-1", group: "F" }, slotB: { kind: "group-2", group: "C" } },
  { matchId: "r32-5",  slotA: { kind: "group-2", group: "E" }, slotB: { kind: "group-2", group: "I" } },
  { matchId: "r32-6",  slotA: { kind: "group-1", group: "I" }, slotB: { kind: "group-3", group: "?" as string } },
  { matchId: "r32-7",  slotA: { kind: "group-1", group: "A" }, slotB: { kind: "group-3", group: "?" as string } },
  { matchId: "r32-8",  slotA: { kind: "group-1", group: "L" }, slotB: { kind: "group-3", group: "?" as string } },
  { matchId: "r32-9",  slotA: { kind: "group-1", group: "D" }, slotB: { kind: "group-3", group: "?" as string } },
  { matchId: "r32-10", slotA: { kind: "group-1", group: "G" }, slotB: { kind: "group-3", group: "?" as string } },
  { matchId: "r32-11", slotA: { kind: "group-1", group: "H" }, slotB: { kind: "group-2", group: "J" } },
  { matchId: "r32-12", slotA: { kind: "group-2", group: "K" }, slotB: { kind: "group-2", group: "L" } },
  { matchId: "r32-13", slotA: { kind: "group-1", group: "B" }, slotB: { kind: "group-3", group: "?" as string } },
  { matchId: "r32-14", slotA: { kind: "group-2", group: "D" }, slotB: { kind: "group-2", group: "G" } },
  { matchId: "r32-15", slotA: { kind: "group-1", group: "J" }, slotB: { kind: "group-2", group: "H" } },
  { matchId: "r32-16", slotA: { kind: "group-1", group: "K" }, slotB: { kind: "group-3", group: "?" as string } },
]

/**
 * FIFA 2026 official third-place bracket distribution table.
 * Source: Wikipedia "Template:2026 FIFA World Cup third-place table".
 *
 * Key: 8 sorted group letters of the qualifying 3rd-place teams (e.g. "ABCDEFJL").
 * Value: 8-char string giving the source group for each of the 8 3rd-place slots,
 *        in column order: r32-7, r32-13, r32-9, r32-3, r32-10, r32-6, r32-16, r32-8.
 *        All are slot B of the respective match.
 *
 * Column→match mapping:
 *   pos 0 → r32-7/B  (W-A, Mexico's match)
 *   pos 1 → r32-13/B (W-B, Switzerland's match)
 *   pos 2 → r32-9/B  (W-D, USA's match)
 *   pos 3 → r32-3/B  (W-E, Germany's match)
 *   pos 4 → r32-10/B (W-G's match)
 *   pos 5 → r32-6/B  (W-I's match)
 *   pos 6 → r32-16/B (W-K's match)
 *   pos 7 → r32-8/B  (W-L's match)
 */
const THIRD_PLACE_COLS = [
  { matchId: "r32-7",  slot: "B" as const },
  { matchId: "r32-13", slot: "B" as const },
  { matchId: "r32-9",  slot: "B" as const },
  { matchId: "r32-3",  slot: "B" as const },
  { matchId: "r32-10", slot: "B" as const },
  { matchId: "r32-6",  slot: "B" as const },
  { matchId: "r32-16", slot: "B" as const },
  { matchId: "r32-8",  slot: "B" as const },
] as const

const RAW_TABLE: Record<string, string> = {
  "ABCDEFGH": "HGBCAFDE",
  "ABCDEFGI": "CGBDAFEI",
  "ABCDEFGJ": "CGBDAFEJ",
  "ABCDEFGK": "CGBDAFEK",
  "ABCDEFGL": "CGBDAFLE",
  "ABCDEFHI": "HEBCAFDI",
  "ABCDEFHJ": "HJBCAFDE",
  "ABCDEFHK": "HEBCAFDK",
  "ABCDEFHL": "HFBCADLE",
  "ABCDEFIJ": "CJBDAFEI",
  "ABCDEFIK": "CEBDAFIK",
  "ABCDEFIL": "CEBDAFLI",
  "ABCDEFJK": "CJBDAFEK",
  "ABCDEFJL": "CJBDAFLE",
  "ABCDEFKL": "CEBDAFLK",
  "ABCDEGHI": "HGBCADEI",
  "ABCDEGHJ": "HGBCADEJ",
  "ABCDEGHK": "HGBCADEK",
  "ABCDEGHL": "HGBCADLE",
  "ABCDEGIJ": "EGBCADIJ",
  "ABCDEGIK": "EGBCADIK",
  "ABCDEGIL": "EGBCADLI",
  "ABCDEGJK": "EGBCADJK",
  "ABCDEGJL": "EGBCADLJ",
  "ABCDEGKL": "EGBCADLK",
  "ABCDEHIJ": "HJBCADEI",
  "ABCDEHIK": "HEBCADIK",
  "ABCDEHIL": "HEBCADLI",
  "ABCDEHJK": "HJBCADEK",
  "ABCDEHJL": "HJBCADLE",
  "ABCDEHKL": "HEBCADLK",
  "ABCDEIJK": "EJBCADIK",
  "ABCDEIJL": "EJBCADLI",
  "ABCDEIKL": "EIBCADLK",
  "ABCDEJKL": "EJBCADLK",
  "ABCDFGHI": "HGBCAFDI",
  "ABCDFGHJ": "HGBCAFDJ",
  "ABCDFGHK": "HGBCAFDK",
  "ABCDFGHL": "CGBDAFLH",
  "ABCDFGIJ": "CGBDAFIJ",
  "ABCDFGIK": "CGBDAFIK",
  "ABCDFGIL": "CGBDAFLI",
  "ABCDFGJK": "CGBDAFJK",
  "ABCDFGJL": "CGBDAFLJ",
  "ABCDFGKL": "CGBDAFLK",
  "ABCDFHIJ": "HJBCAFDI",
  "ABCDFHIK": "HFBCADIK",
  "ABCDFHIL": "HFBCADLI",
  "ABCDFHJK": "HJBCAFDK",
  "ABCDFHJL": "CJBDAFLH",
  "ABCDFHKL": "HFBCADLK",
  "ABCDFIJK": "CJBDAFIK",
  "ABCDFIJL": "CJBDAFLI",
  "ABCDFIKL": "CIBDAFLK",
  "ABCDFJKL": "CJBDAFLK",
  "ABCDGHIJ": "HGBCADIJ",
  "ABCDGHIK": "HGBCADIK",
  "ABCDGHIL": "HGBCADLI",
  "ABCDGHJK": "HGBCADJK",
  "ABCDGHJL": "HGBCADLJ",
  "ABCDGHKL": "HGBCADLK",
  "ABCDGIJK": "CJBDAGIK",
  "ABCDGIJL": "CJBDAGLI",
  "ABCDGIKL": "IGBCADLK",
  "ABCDGJKL": "CJBDAGLK",
  "ABCDHIJK": "HJBCADIK",
  "ABCDHIJL": "HJBCADLI",
  "ABCDHIKL": "HIBCADLK",
  "ABCDHJKL": "HJBCADLK",
  "ABCDIJKL": "IJBCADLK",
  "ABCEFGHI": "HGBCAFEI",
  "ABCEFGHJ": "HGBCAFEJ",
  "ABCEFGHK": "HGBCAFEK",
  "ABCEFGHL": "HGBCAFLE",
  "ABCEFGIJ": "EGBCAFIJ",
  "ABCEFGIK": "EGBCAFIK",
  "ABCEFGIL": "EGBCAFLI",
  "ABCEFGJK": "EGBCAFJK",
  "ABCEFGJL": "EGBCAFLJ",
  "ABCEFGKL": "EGBCAFLK",
  "ABCEFHIJ": "HJBCAFEI",
  "ABCEFHIK": "HEBCAFIK",
  "ABCEFHIL": "HEBCAFLI",
  "ABCEFHJK": "HJBCAFEK",
  "ABCEFHJL": "HJBCAFLE",
  "ABCEFHKL": "HEBCAFLK",
  "ABCEFIJK": "EJBCAFIK",
  "ABCEFIJL": "EJBCAFLI",
  "ABCEFIKL": "EIBCAFLK",
  "ABCEFJKL": "EJBCAFLK",
  "ABCEGHIJ": "HJBCAGEI",
  "ABCEGHIK": "EGBCAHIK",
  "ABCEGHIL": "EGBCAHLI",
  "ABCEGHJK": "HJBCAGEK",
  "ABCEGHJL": "HJBCAGLE",
  "ABCEGHKL": "EGBCAHLK",
  "ABCEGIJK": "EJBCAGIK",
  "ABCEGIJL": "EJBCAGLI",
  "ABCEGIKL": "EGBAICLK",
  "ABCEGJKL": "EJBCAGLK",
  "ABCEHIJK": "EJBCAHIK",
  "ABCEHIJL": "EJBCAHLI",
  "ABCEHIKL": "EIBCAHLK",
  "ABCEHJKL": "EJBCAHLK",
  "ABCEIJKL": "EJBAICLK",
  "ABCFGHIJ": "HGBCAFIJ",
  "ABCFGHIK": "HGBCAFIK",
  "ABCFGHIL": "HGBCAFLI",
  "ABCFGHJK": "HGBCAFJK",
  "ABCFGHJL": "HGBCAFLJ",
  "ABCFGHKL": "HGBCAFLK",
  "ABCFGIJK": "CJBFAGIK",
  "ABCFGIJL": "CJBFAGLI",
  "ABCFGIKL": "IGBCAFLK",
  "ABCFGJKL": "CJBFAGLK",
  "ABCFHIJK": "HJBCAFIK",
  "ABCFHIJL": "HJBCAFLI",
  "ABCFHIKL": "HIBCAFLK",
  "ABCFHJKL": "HJBCAFLK",
  "ABCFIJKL": "IJBCAFLK",
  "ABCGHIJK": "HJBCAGIK",
  "ABCGHIJL": "HJBCAGLI",
  "ABCGHIKL": "IGBCAHLK",
  "ABCGHJKL": "HJBCAGLK",
  "ABCGIJKL": "IJBCAGLK",
  "ABCHIJKL": "IJBCAHLK",
  "ABDEFGHI": "HGBDAFEI",
  "ABDEFGHJ": "HGBDAFEJ",
  "ABDEFGHK": "HGBDAFEK",
  "ABDEFGHL": "HGBDAFLE",
  "ABDEFGIJ": "EGBDAFIJ",
  "ABDEFGIK": "EGBDAFIK",
  "ABDEFGIL": "EGBDAFLI",
  "ABDEFGJK": "EGBDAFJK",
  "ABDEFGJL": "EGBDAFLJ",
  "ABDEFGKL": "EGBDAFLK",
  "ABDEFHIJ": "HJBDAFEI",
  "ABDEFHIK": "HEBDAFIK",
  "ABDEFHIL": "HEBDAFLI",
  "ABDEFHJK": "HJBDAFEK",
  "ABDEFHJL": "HJBDAFLE",
  "ABDEFHKL": "HEBDAFLK",
  "ABDEFIJK": "EJBDAFIK",
  "ABDEFIJL": "EJBDAFLI",
  "ABDEFIKL": "EIBDAFLK",
  "ABDEFJKL": "EJBDAFLK",
  "ABDEGHIJ": "HJBDAGEI",
  "ABDEGHIK": "EGBDAHIK",
  "ABDEGHIL": "EGBDAHLI",
  "ABDEGHJK": "HJBDAGEK",
  "ABDEGHJL": "HJBDAGLE",
  "ABDEGHKL": "EGBDAHLK",
  "ABDEGIJK": "EJBDAGIK",
  "ABDEGIJL": "EJBDAGLI",
  "ABDEGIKL": "EGBAIDLK",
  "ABDEGJKL": "EJBDAGLK",
  "ABDEHIJK": "EJBDAHIK",
  "ABDEHIJL": "EJBDAHLI",
  "ABDEHIKL": "EIBDAHLK",
  "ABDEHJKL": "EJBDAHLK",
  "ABDEIJKL": "EJBAIDLK",
  "ABDFGHIJ": "HGBDAFIJ",
  "ABDFGHIK": "HGBDAFIK",
  "ABDFGHIL": "HGBDAFLI",
  "ABDFGHJK": "HGBDAFJK",
  "ABDFGHJL": "HGBDAFLJ",
  "ABDFGHKL": "HGBDAFLK",
  "ABDFGIJK": "FJBDAGIK",
  "ABDFGIJL": "FJBDAGLI",
  "ABDFGIKL": "IGBDAFLK",
  "ABDFGJKL": "FJBDAGLK",
  "ABDFHIJK": "HJBDAFIK",
  "ABDFHIJL": "HJBDAFLI",
  "ABDFHIKL": "HIBDAFLK",
  "ABDFHJKL": "HJBDAFLK",
  "ABDFIJKL": "IJBDAFLK",
  "ABDGHIJK": "HJBDAGIK",
  "ABDGHIJL": "HJBDAGLI",
  "ABDGHIKL": "IGBDAHLK",
  "ABDGHJKL": "HJBDAGLK",
  "ABDGIJKL": "IJBDAGLK",
  "ABDHIJKL": "IJBDAHLK",
  "ABEFGHIJ": "HJBFAGEI",
  "ABEFGHIK": "EGBFAHIK",
  "ABEFGHIL": "EGBFAHLI",
  "ABEFGHJK": "HJBFAGEK",
  "ABEFGHJL": "HJBFAGLE",
  "ABEFGHKL": "EGBFAHLK",
  "ABEFGIJK": "EJBFAGIK",
  "ABEFGIJL": "EJBFAGLI",
  "ABEFGIKL": "EGBAIFLK",
  "ABEFGJKL": "EJBFAGLK",
  "ABEFHIJK": "EJBFAHIK",
  "ABEFHIJL": "EJBFAHLI",
  "ABEFHIKL": "EIBFAHLK",
  "ABEFHJKL": "EJBFAHLK",
  "ABEFIJKL": "EJBAIFLK",
  "ABEGHIJK": "EJBAHGIK",
  "ABEGHIJL": "EJBAHGLI",
  "ABEGHIKL": "EGBAIHLK",
  "ABEGHJKL": "EJBAHGLK",
  "ABEGIJKL": "EJBAIGLK",
  "ABEHIJKL": "EJBAIHLK",
  "ABFGHIJK": "HJBFAGIK",
  "ABFGHIJL": "HJBFAGLI",
  "ABFGHIKL": "HGBAIFLK",
  "ABFGHJKL": "HJBFAGLK",
  "ABFGIJKL": "IJBFAGLK",
  "ABFHIJKL": "HJBAIFLK",
  "ABGHIJKL": "HJBAIGLK",
  "ACDEFGHI": "HGECAFDI",
  "ACDEFGHJ": "HGJCAFDE",
  "ACDEFGHK": "HGECAFDK",
  "ACDEFGHL": "HGFCADLE",
  "ACDEFGIJ": "CGJDAFEI",
  "ACDEFGIK": "CGEDAFIK",
  "ACDEFGIL": "CGEDAFLI",
  "ACDEFGJK": "CGJDAFEK",
  "ACDEFGJL": "CGJDAFLE",
  "ACDEFGKL": "CGEDAFLK",
  "ACDEFHIJ": "HJECAFDI",
  "ACDEFHIK": "HEFCADIK",
  "ACDEFHIL": "HEFCADLI",
  "ACDEFHJK": "HJECAFDK",
  "ACDEFHJL": "HJFCADLE",
  "ACDEFHKL": "HEFCADLK",
  "ACDEFIJK": "CJEDAFIK",
  "ACDEFIJL": "CJEDAFLI",
  "ACDEFIKL": "CEIDAFLK",
  "ACDEFJKL": "CJEDAFLK",
  "ACDEGHIJ": "HGJCADEI",
  "ACDEGHIK": "HGECADIK",
  "ACDEGHIL": "HGECADLI",
  "ACDEGHJK": "HGJCADEK",
  "ACDEGHJL": "HGJCADLE",
  "ACDEGHKL": "HGECADLK",
  "ACDEGIJK": "EGJCADIK",
  "ACDEGIJL": "EGJCADLI",
  "ACDEGIKL": "EGICADLK",
  "ACDEGJKL": "EGJCADLK",
  "ACDEHIJK": "HJECADIK",
  "ACDEHIJL": "HJECADLI",
  "ACDEHIKL": "HEICADLK",
  "ACDEHJKL": "HJECADLK",
  "ACDEIJKL": "EJICADLK",
  "ACDFGHIJ": "HGJCAFDI",
  "ACDFGHIK": "HGFCADIK",
  "ACDFGHIL": "HGFCADLI",
  "ACDFGHJK": "HGJCAFDK",
  "ACDFGHJL": "CGJDAFLH",
  "ACDFGHKL": "HGFCADLK",
  "ACDFGIJK": "CGJDAFIK",
  "ACDFGIJL": "CGJDAFLI",
  "ACDFGIKL": "CGIDAFLK",
  "ACDFGJKL": "CGJDAFLK",
  "ACDFHIJK": "HJFCADIK",
  "ACDFHIJL": "HJFCADLI",
  "ACDFHIKL": "HFICADLK",
  "ACDFHJKL": "HJFCADLK",
  "ACDFIJKL": "CJIDAFLK",
  "ACDGHIJK": "HGJCADIK",
  "ACDGHIJL": "HGJCADLI",
  "ACDGHIKL": "HGICADLK",
  "ACDGHJKL": "HGJCADLK",
  "ACDGIJKL": "IGJCADLK",
  "ACDHIJKL": "HJICADLK",
  "ACEFGHIJ": "HGJCAFEI",
  "ACEFGHIK": "HGECAFIK",
  "ACEFGHIL": "HGECAFLI",
  "ACEFGHJK": "HGJCAFEK",
  "ACEFGHJL": "HGJCAFLE",
  "ACEFGHKL": "HGECAFLK",
  "ACEFGIJK": "EGJCAFIK",
  "ACEFGIJL": "EGJCAFLI",
  "ACEFGIKL": "EGICAFLK",
  "ACEFGJKL": "EGJCAFLK",
  "ACEFHIJK": "HJECAFIK",
  "ACEFHIJL": "HJECAFLI",
  "ACEFHIKL": "HEICAFLK",
  "ACEFHJKL": "HJECAFLK",
  "ACEFIJKL": "EJICAFLK",
  "ACEGHIJK": "EGJCAHIK",
  "ACEGHIJL": "EGJCAHLI",
  "ACEGHIKL": "EGICAHLK",
  "ACEGHJKL": "EGJCAHLK",
  "ACEGIJKL": "EJICAGLK",
  "ACEHIJKL": "EJICAHLK",
  "ACFGHIJK": "HGJCAFIK",
  "ACFGHIJL": "HGJCAFLI",
  "ACFGHIKL": "HGICAFLK",
  "ACFGHJKL": "HGJCAFLK",
  "ACFGIJKL": "IGJCAFLK",
  "ACFHIJKL": "HJICAFLK",
  "ACGHIJKL": "HJICAGLK",
  "ADEFGHIJ": "HGJDAFEI",
  "ADEFGHIK": "HGEDAFIK",
  "ADEFGHIL": "HGEDAFLI",
  "ADEFGHJK": "HGJDAFEK",
  "ADEFGHJL": "HGJDAFLE",
  "ADEFGHKL": "HGEDAFLK",
  "ADEFGIJK": "EGJDAFIK",
  "ADEFGIJL": "EGJDAFLI",
  "ADEFGIKL": "EGIDAFLK",
  "ADEFGJKL": "EGJDAFLK",
  "ADEFHIJK": "HJEDAFIK",
  "ADEFHIJL": "HJEDAFLI",
  "ADEFHIKL": "HEIDAFLK",
  "ADEFHJKL": "HJEDAFLK",
  "ADEFIJKL": "EJIDAFLK",
  "ADEGHIJK": "EGJDAHIK",
  "ADEGHIJL": "EGJDAHLI",
  "ADEGHIKL": "EGIDAHLK",
  "ADEGHJKL": "EGJDAHLK",
  "ADEGIJKL": "EJIDAGLK",
  "ADEHIJKL": "EJIDAHLK",
  "ADFGHIJK": "HGJDAFIK",
  "ADFGHIJL": "HGJDAFLI",
  "ADFGHIKL": "HGIDAFLK",
  "ADFGHJKL": "HGJDAFLK",
  "ADFGIJKL": "IGJDAFLK",
  "ADFHIJKL": "HJIDAFLK",
  "ADGHIJKL": "HJIDAGLK",
  "AEFGHIJK": "EGJFAHIK",
  "AEFGHIJL": "EGJFAHLI",
  "AEFGHIKL": "EGIFAHLK",
  "AEFGHJKL": "EGJFAHLK",
  "AEFGIJKL": "EJIFAGLK",
  "AEFHIJKL": "EJIFAHLK",
  "AEGHIJKL": "EJIAHGLK",
  "AFGHIJKL": "HJIFAGLK",
  "BCDEFGHI": "CGBDHFEI",
  "BCDEFGHJ": "HGBCJFDE",
  "BCDEFGHK": "CGBDHFEK",
  "BCDEFGHL": "CGBDHFLE",
  "BCDEFGIJ": "CGBDJFEI",
  "BCDEFGIK": "CGBDEFIK",
  "BCDEFGIL": "CGBDEFLI",
  "BCDEFGJK": "CGBDJFEK",
  "BCDEFGJL": "CGBDJFLE",
  "BCDEFGKL": "CGBDEFLK",
  "BCDEFHIJ": "CJBDHFEI",
  "BCDEFHIK": "CEBDHFIK",
  "BCDEFHIL": "CEBDHFLI",
  "BCDEFHJK": "CJBDHFEK",
  "BCDEFHJL": "CJBDHFLE",
  "BCDEFHKL": "CEBDHFLK",
  "BCDEFIJK": "CJBDEFIK",
  "BCDEFIJL": "CJBDEFLI",
  "BCDEFIKL": "CEBDIFLK",
  "BCDEFJKL": "CJBDEFLK",
  "BCDEGHIJ": "HGBCJDEI",
  "BCDEGHIK": "EGBCHDIK",
  "BCDEGHIL": "EGBCHDLI",
  "BCDEGHJK": "HGBCJDEK",
  "BCDEGHJL": "HGBCJDLE",
  "BCDEGHKL": "EGBCHDLK",
  "BCDEGIJK": "EGBCJDIK",
  "BCDEGIJL": "EGBCJDLI",
  "BCDEGIKL": "EGBCIDLK",
  "BCDEGJKL": "EGBCJDLK",
  "BCDEHIJK": "EJBCHDIK",
  "BCDEHIJL": "EJBCHDLI",
  "BCDEHIKL": "EIBCHDLK",
  "BCDEHJKL": "EJBCHDLK",
  "BCDEIJKL": "EJBCIDLK",
  "BCDFGHIJ": "HGBCJFDI",
  "BCDFGHIK": "CGBDHFIK",
  "BCDFGHIL": "CGBDHFLI",
  "BCDFGHJK": "HGBCJFDK",
  "BCDFGHJL": "CGBDHFLJ",
  "BCDFGHKL": "CGBDHFLK",
  "BCDFGIJK": "CGBDJFIK",
  "BCDFGIJL": "CGBDJFLI",
  "BCDFGIKL": "CGBDIFLK",
  "BCDFGJKL": "CGBDJFLK",
  "BCDFHIJK": "CJBDHFIK",
  "BCDFHIJL": "CJBDHFLI",
  "BCDFHIKL": "CIBDHFLK",
  "BCDFHJKL": "CJBDHFLK",
  "BCDFIJKL": "CJBDIFLK",
  "BCDGHIJK": "HGBCJDIK",
  "BCDGHIJL": "HGBCJDLI",
  "BCDGHIKL": "HGBCIDLK",
  "BCDGHJKL": "HGBCJDLK",
  "BCDGIJKL": "IGBCJDLK",
  "BCDHIJKL": "HJBCIDLK",
  "BCEFGHIJ": "HGBCJFEI",
  "BCEFGHIK": "EGBCHFIK",
  "BCEFGHIL": "EGBCHFLI",
  "BCEFGHJK": "HGBCJFEK",
  "BCEFGHJL": "HGBCJFLE",
  "BCEFGHKL": "EGBCHFLK",
  "BCEFGIJK": "EGBCJFIK",
  "BCEFGIJL": "EGBCJFLI",
  "BCEFGIKL": "EGBCIFLK",
  "BCEFGJKL": "EGBCJFLK",
  "BCEFHIJK": "EJBCHFIK",
  "BCEFHIJL": "EJBCHFLI",
  "BCEFHIKL": "EIBCHFLK",
  "BCEFHJKL": "EJBCHFLK",
  "BCEFIJKL": "EJBCIFLK",
  "BCEGHIJK": "EJBCHGIK",
  "BCEGHIJL": "EJBCHGLI",
  "BCEGHIKL": "EGBCIHLK",
  "BCEGHJKL": "EJBCHGLK",
  "BCEGIJKL": "EJBCIGLK",
  "BCEHIJKL": "EJBCIHLK",
  "BCFGHIJK": "HGBCJFIK",
  "BCFGHIJL": "HGBCJFLI",
  "BCFGHIKL": "HGBCIFLK",
  "BCFGHJKL": "HGBCJFLK",
  "BCFGIJKL": "IGBCJFLK",
  "BCFHIJKL": "HJBCIFLK",
  "BCGHIJKL": "HJBCIGLK",
  "BDEFGHIJ": "HGBDJFEI",
  "BDEFGHIK": "EGBDHFIK",
  "BDEFGHIL": "EGBDHFLI",
  "BDEFGHJK": "HGBDJFEK",
  "BDEFGHJL": "HGBDJFLE",
  "BDEFGHKL": "EGBDHFLK",
  "BDEFGIJK": "EGBDJFIK",
  "BDEFGIJL": "EGBDJFLI",
  "BDEFGIKL": "EGBDIFLK",
  "BDEFGJKL": "EGBDJFLK",
  "BDEFHIJK": "EJBDHFIK",
  "BDEFHIJL": "EJBDHFLI",
  "BDEFHIKL": "EIBDHFLK",
  "BDEFHJKL": "EJBDHFLK",
  "BDEFIJKL": "EJBDIFLK",
  "BDEGHIJK": "EJBDHGIK",
  "BDEGHIJL": "EJBDHGLI",
  "BDEGHIKL": "EGBDIHLK",
  "BDEGHJKL": "EJBDHGLK",
  "BDEGIJKL": "EJBDIGLK",
  "BDEHIJKL": "EJBDIHLK",
  "BDFGHIJK": "HGBDJFIK",
  "BDFGHIJL": "HGBDJFLI",
  "BDFGHIKL": "HGBDIFLK",
  "BDFGHJKL": "HGBDJFLK",
  "BDFGIJKL": "IGBDJFLK",
  "BDFHIJKL": "HJBDIFLK",
  "BDGHIJKL": "HJBDIGLK",
  "BEFGHIJK": "EJBFHGIK",
  "BEFGHIJL": "EJBFHGLI",
  "BEFGHIKL": "EGBFIHLK",
  "BEFGHJKL": "EJBFHGLK",
  "BEFGIJKL": "EJBFIGLK",
  "BEFHIJKL": "EJBFIHLK",
  "BEGHIJKL": "EJIBHGLK",
  "BFGHIJKL": "HJBFIGLK",
  "CDEFGHIJ": "CGJDHFEI",
  "CDEFGHIK": "CGEDHFIK",
  "CDEFGHIL": "CGEDHFLI",
  "CDEFGHJK": "CGJDHFEK",
  "CDEFGHJL": "CGJDHFLE",
  "CDEFGHKL": "CGEDHFLK",
  "CDEFGIJK": "CGEDJFIK",
  "CDEFGIJL": "CGEDJFLI",
  "CDEFGIKL": "CGEDIFLK",
  "CDEFGJKL": "CGEDJFLK",
  "CDEFHIJK": "CJEDHFIK",
  "CDEFHIJL": "CJEDHFLI",
  "CDEFHIKL": "CEIDHFLK",
  "CDEFHJKL": "CJEDHFLK",
  "CDEFIJKL": "CJEDIFLK",
  "CDEGHIJK": "EGJCHDIK",
  "CDEGHIJL": "EGJCHDLI",
  "CDEGHIKL": "EGICHDLK",
  "CDEGHJKL": "EGJCHDLK",
  "CDEGIJKL": "EGICJDLK",
  "CDEHIJKL": "EJICHDLK",
  "CDFGHIJK": "CGJDHFIK",
  "CDFGHIJL": "CGJDHFLI",
  "CDFGHIKL": "CGIDHFLK",
  "CDFGHJKL": "CGJDHFLK",
  "CDFGIJKL": "CGIDJFLK",
  "CDFHIJKL": "CJIDHFLK",
  "CDGHIJKL": "HGICJDLK",
  "CEFGHIJK": "EGJCHFIK",
  "CEFGHIJL": "EGJCHFLI",
  "CEFGHIKL": "EGICHFLK",
  "CEFGHJKL": "EGJCHFLK",
  "CEFGIJKL": "EGICJFLK",
  "CEFHIJKL": "EJICHFLK",
  "CEGHIJKL": "EJICHGLK",
  "CFGHIJKL": "HGICJFLK",
  "DEFGHIJK": "EGJDHFIK",
  "DEFGHIJL": "EGJDHFLI",
  "DEFGHIKL": "EGIDHFLK",
  "DEFGHJKL": "EGJDHFLK",
  "DEFGIJKL": "EGIDJFLK",
  "DEFHIJKL": "EJIDHFLK",
  "DEGHIJKL": "EJIDHGLK",
  "DFGHIJKL": "HGIDJFLK",
  "EFGHIJKL": "EJIFHGLK",
}

export const THIRD_PLACE_TABLE: Record<string, ThirdSlot[]> = Object.fromEntries(
  Object.entries(RAW_TABLE).map(([key, groups]) => [
    key,
    groups.split("").map((g, i) => ({ ...THIRD_PLACE_COLS[i], group: g })),
  ]),
)
